#!/bin/bash
BASE_DIR=$(cd `dirname $BASH_SOURCE`/../.. && pwd)

export BASE_DIR=$BASE_DIR
export ADMINISTRATOR_HOME=$BASE_DIR/administrator
export COMPONENTS_HOME=$BASE_DIR/components
export APPLICATIONS_HOME=$BASE_DIR/applications
export INSTALLER_HOME=$ADMINISTRATOR_HOME/installer

echo "BASE_DIR=$BASE_DIR"
echo "ADMINISTRATOR_HOME=$ADMINISTRATOR_HOME"
echo "COMPONENTS_HOME=$COMPONENTS_HOME"
echo "APPLICATIONS_HOME=$APPLICATIONS_HOME"
echo "INSTALLER_HOME=$INSTALLER_HOME"